### ISSUE TITLE
Android Navigationbar blocks chat send button while typing

### ISSUE THREAD

**Issue by Icoryx** [tommyxchow/frosty#105]
When you write a message in chat and try to send it while the keyboard is still open the navigationbar overlaps with the send button so you have to tap somewhere to close the keyboard to be able to send the message. I'm on a Oneplus 8t with android 12.
![Screenshot_2022-04-06-01-28-41-12_1f6a23d21ed6c97d5400a99f48294dc8](https://user-images.githubusercontent.com/17325607/161867315-3403a149-24a1-403b-af82-abe73b31700d.jpg)

**Comment by tommyxchow** [comment]
Thanks for the report, it's reproducible on my end as well. Will look into it.

**Comment by tommyxchow** [comment]
Unfortunately, this is a weird Android behavior that I [can't override](https://stackoverflow.com/questions/53030140/flutter-how-to-show-onscreen-keyboard-without-androids-bottom-navigation-bar-o). As an alternative solution, I've changed the keyboard action button to send the message in #119. Sorry about this, and hopefully the workaround is sufficient.
