### ISSUE TITLE
Zero Width Emotes not working properly

### ISSUE THREAD

**Issue by Icoryx** [tommyxchow/frosty#110]
The Zerowidth Emotes from 7TV aren't placed onto other emojis
![Screenshot_2022-04-15-22-45-26-12_1f6a23d21ed6c97d5400a99f48294dc8](https://user-images.githubusercontent.com/17325607/163630458-ca6d9c88-e799-4455-a31c-bd79cb379b57.jpg)

**Comment by tommyxchow** [comment]
Looks like this happens randomly when fetching the emotes 7TV's API (the order of some of their response fields are ordered randomly and I didn't check for this). I've found a fix already and will work on it ASAP. Thanks again for reporting!
