### ISSUE TITLE
Enter on external keyboard not sending message

### ISSUE THREAD

**Issue by Eradik1** [tommyxchow/frosty#114]
When using an external keyboard, pressing enter in chat goes to a new line and does not send the message. May we please have a toggle so that it sends when we push enter as opposed to having to tap the send button? Thanks

**Comment by tommyxchow** [comment]
I'll add a setting for this in the next upcoming patch, thank you for bringing it up.

**Comment by Eradik1** [comment]
That is awesome, thank you so much!
