### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#132]
I would like a way to block ads. This would most likely get the app pulled from stores so maybe you could only integrate this feature into the manual apk/ipa downloads only.

**Comment by tommyxchow** [comment]
As much as I'd like to have an ad block implemented for the APKs, it's beyond my skillset. Furthermore, I fear it will be an endless cat-and-mouse game with Twitch constantly circumventing new ad block solutions. I am closing this issue as "not planned" until a solid solution arises.

**Comment by StephanBruh** [comment]
Since we have 'proxy' adblock now. Would you maybe add support for this?
