### ISSUE TITLE
Vods

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#134]
I would like the feature to be able to watch vods.

**Comment by tommyxchow** [comment]
VODs are definitely a really good feature to have in the app. The reason I hadn't implemented it is due to the lack of documentation regarding obtaining the VOD chats.

I'll do some more investigating and see what I can do. This will probably be the next major feature to work on if possible.

**Comment by tommyxchow** [comment]
Late update: It seems like Twitch has removed the public endpoint that was used to get VOD chat logs. There _are_ other ways of getting the chat logs, but they're only accessible through Twitch's private and undocumented GraphQL APIs. 

Usage of these APIs has been heavily implied to violate the Twitch TOS, so I probably won't be able to get VODs with chat done. Hopefully, VOD chats are available in the official Twitch API soon. Really sorry about this.

**Comment by kamild1996** [comment]
Has anything about the Twitch API changed in the last ~3 years? Still no chance for VODs?
