### ISSUE TITLE
After unpausing a stream the transparent square background of the play button will sometimes keep being rendered

### ISSUE THREAD

**Issue by keineahnungking** [tommyxchow/frosty#137]
**Describe the bug**

After unpausing a stream the transparent square background of the play button will sometimes keep being rendered

**To Reproduce**
Steps to reproduce the behavior: Pause and unpause a stream and you can see a box where the play button was.
**Expected behavior**
Nothing should be rendered on top of the stream.

**Screenshots**
![7FE462E0-A63C-4069-8D9D-3E7396BC9847](https://user-images.githubusercontent.com/105888328/171489285-5afee0ea-3f8b-4fcd-9eac-505abebbe2e4.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2017
 - OS: iOS 14.2
 - App Version: 1.4.1 (23)

**Comment by tommyxchow** [comment]
This seems like a side effect with older versions of iOS/Safari. I'm getting similar results with the overlay on the iOS simulator on iOS 14.2 as well (the entire screen has a hint of gray after pausing and unpausing).

I can add some JavaScript that removes the video overlay HTML in Twitch's web player entirely, so this shouldn't happen again. Keep in mind that this solution _might_ stop working randomly if Twitch decides to refactor/rename their HTML in the future. If that ever does happen, I'll deploy a quick hotfix that addresses the renames.

One caveat is that error messages from Twitch will no longer show up (e.g., the Error 3000 and "Click Here to Reload Player"). I'll do a little more investigating before deciding whether or not to implement the HTML removal.

**Comment by tommyxchow** [comment]
Unfortunately removing the overlay causes some weird side effects. Since this is ultimately on Twitch's end, I can't do much to fix it.

For what it's worth, I've noticed that tapping outside the button to unpause seems to prevent the box from appearing. Also, it seems like tapping the overlay once or twice (sometimes a couple) makes the box disappear as well.
