### ISSUE TITLE
I can't log into the app. After giving it permission to my twitch account it just goes back to streams and I'm not logged. I'm on Android 10

### ISSUE THREAD

**Issue by Szado33** [tommyxchow/frosty#147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13, Pixel 6]
 - OS: [e.g. iOS 15, Android 12]
 - App Version: [check in Settings -> Other -> About Frosty. e.g. v1.4.1 (22)]

**Additional context**

**Comment by tommyxchow** [comment]
I'm streamlining the login method that hopefully will fix this odd behavior.

Closing this, a duplicate of #139.
