### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by merscever** [tommyxchow/frosty#148]
I think having a discord for the app would be a better place to attract supporters and get more feedback, not everyone has a github account

**Comment by tyrohellion** [comment]
I think so too

**Comment by tommyxchow** [comment]
Hey there, sorry for the very late response. I've considered making a Discord server before but sadly I don't think I'll have the time to actively maintain and organize it. Frosty is just a side project that I work on during my free time (which I've been slowly losing) and I feel it would be unfair to most people if I won't be active there.

I'll look into making a subreddit that I can check on and off. Hopefully, that'll be a feasible alternative.

**Comment by merscever** [comment]
Patreon would be best then, I understand that its a side project but you made best third party on ios so i would want to support you monthly
