### ISSUE TITLE
[SUGGESTION] Add a popup to send the copied message in chat

### ISSUE THREAD

**Issue by humphreyyy** [tommyxchow/frosty#171]
Oftentimes when I copy a message I just wanna send that same message in chat. I really like how you can hold to copy now, but its still a bit clunky to then focus the chat window, tap it again to bring up the paste option, paste it, send it, and then collapse the chat again. 

It would be really nice if there was a way to just send that copied message with one tap. 
Really appreciate this app btw!

**Comment by tommyxchow** [comment]
Thank you for the suggestion! This is definitely a nice quality-of-life feature I've noticed in other mobile/web apps as well, so I'll have it added to Frosty as well.

**Comment by tommyxchow** [comment]
Update: I've added a paste button to the notification, along with an option to have the notification on the bottom of the chat for better ergonomics:

[paste-demo.webm](https://user-images.githubusercontent.com/54859075/183227329-a533857f-e215-4001-a871-f1fe84820d3e.webm)

Thanks again for the suggestion. Will be releasing it in the next update!
