### ISSUE TITLE
Custom Font Size

### ISSUE THREAD

**Issue by recon88** [tommyxchow/frosty#183]
I really appreciate the font size slider, but 20 isn't enough in my case. I need the text to be really big on the screen I'm using.
Can we instead get a field that lets the user put in a custom value? Or just allow the slider to go up to around 72.

**Comment by tommyxchow** [comment]
I would recommend a system setting that adjusts the font size of apps (if that exists of course). Frosty was made to support smaller devices like phones, so I don't want to fill the options with extraneous values (unless there is outstanding demand of course). Apologies.
