### ISSUE TITLE
Suggestion: Support for Twitch Pronouns

### ISSUE THREAD

**Issue by mrhyde1st** [tommyxchow/frosty#185]
Could we have a toggle to enable [Twitch Pronouns](https://pronouns.alejo.io/)

**Comment by tommyxchow** [comment]
So I did some investigating and probably won't be able to get this done. 

AFAIK, the pronouns API works on a per-user basis, so we'd have to make a single request for pronouns each and every time a user appears in chat. This can easily cause some performance issues and other side effects, especially in really fast chats where hundreds of messages are being sent per second. I could _probably_ figure something out with caching but it'd be a bit excessive for a relatively minor feature.

Don't get me wrong—the extension is great, but in terms of usage and stability, it's not of the same caliber as 7TV, BTTV, and FFZ (thousands vs millions of users), so supporting it is low on my priority list. Hopefully, Twitch will add official IRC support for pronouns soon, but for now, I'm going to close this issue. Thanks.
