### ISSUE TITLE
PiP when stream is minimized

### ISSUE THREAD

**Issue by jboots07** [tommyxchow/frosty#186]
Would there by any way to have the default action of when you go back to streams list have the currently playing stream go to a PiP window like the native Twitch App does, rather than requiring a user interaction and tapping on the button?

**Comment by tommyxchow** [comment]
Hello and thanks for opening the issue. I'd love to have this feature but it's more complicated than it seems. Will look into it again soon.

Closing this as it's a duplicate of #133.
