### ISSUE TITLE
Pressing back button with emote menu open closes the stream

### ISSUE THREAD

**Issue by HeelMePlz** [tommyxchow/frosty#188]
**Describe the bug**
When the emote menu is open, pressing the back button will close the stream and take you back to the menu screen, instead of closing the emote menu.

**To Reproduce**
1. Open a stream
2. Open the emote menu
3. Press the back button

**Expected behavior**
The emote menu closes while the stream and it's chat is still open.

**Screenshots**

Screenshot showing when the emote menu is open:
![image](https://user-images.githubusercontent.com/78705543/188220368-c3af056c-8c0b-4679-b5d3-e4e4d4704cad.png)

Screenshot showing what happens after pressing the back button at that point:
![image](https://user-images.githubusercontent.com/78705543/188220596-509e229f-2be5-4943-9920-33d39ae04161.png)

Screenshot showing what I would expect to happen instead:
![image](https://user-images.githubusercontent.com/78705543/188220697-5c7b61e1-225d-44a5-8f26-2a2569b5f846.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - App Version: Version 2.2.0

**Comment by tommyxchow** [comment]
It's "hidden" behaviors like this that I miss from the official Twitch app, so thank you so much for opening the issue.

**Comment by HeelMePlz** [comment]
My pleasure! I wasn't sure if it was really an issue and thought it could have been my own nit-picking, but I can submit more as I use the app and you can decide whether it is intentional behaviour or not! ☺️❤️
