### ISSUE TITLE
Feature Request: Vertical chat feature in Galaxy Fold and iPad

### ISSUE THREAD

**Issue by Arc-Jung** [tommyxchow/frosty#195]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20220910_104446](https://user-images.githubusercontent.com/43470915/189464374-4f36fe4e-c0f6-49c7-be22-b741321e0c1b.jpg)
I use iPad and Galaxy Fold. But there are too many bezels on my iPad and Galaxy Fold.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/43470915/189464131-24d79613-fb33-4ea8-b718-aa7b4f191eaa.png)
I want Vertical chat feature such as this screenshot.

**Comment by Arc-Jung** [comment]
please solve my issue. I sponsed this project. If clear this issue, i will spons one more time.

**Comment by tommyxchow** [comment]
Thank you so much for the sponsor! I'll see if I can add a setting that forces the chat to be under the video in landscape mode.

**Comment by tommyxchow** [comment]
Hey there, quick update! I've added an option to force the chat to be on the bottom (vertical) when in landscape mode. You can see it in action here:

https://user-images.githubusercontent.com/54859075/189763964-c9ef4079-044a-444d-aa80-8b6c9fcf1a17.mp4

I've only tested it on some emulators, so hopefully, it will work for you as well. I'll push out an update ASAP.

**Comment by Arc-Jung** [comment]
You are good developer. I will install new version. I will back soon!

**Comment by Arc-Jung** [comment]
I am come back! I used updated version. I am very satisfied.
Therefore i sponsed at 10 $!
