### ISSUE TITLE
Add Subscriber Emotes

### ISSUE THREAD

**Issue by j-zelinski** [tommyxchow/frosty#197]
The emote selection is missing any subscriber emotes that are available to be used.

It should show the current streamer's emotes at the top based on the channel you are in and then all the other emotes you get from other subscriptions.

**Comment by alienware377** [comment]
I seriously thought it was a bug that sub emotes weren't in the app. I couldn't imagine someone making a twitch app that adds support for 7tv/etc emotes but lacks sub emotes.... I guess this app is made for people who simply don't sub to channels?

**Comment by Cyborgeagle** [comment]
If it's not a bug then I support this feature request.

> I seriously thought it was a bug that sub emotes weren't in the app. I couldn't imagine someone making a twitch app that adds support for 7tv/etc emotes but lacks sub emotes.... I guess this app is made for people who simply don't sub to channels?

I guess probably made more for lurker.
