### ISSUE TITLE
tvOS Version

### ISSUE THREAD

**Issue by humphreyyy** [tommyxchow/frosty#200]
This is probably a long shot, but I would love a tvOS version of the app. The twitch app suffers the same problems of the iOS app (no 7tv/bttv etc emotes). 

I can help with testing if needed as well <3

**Comment by tommyxchow** [comment]
Hey there, unfortunately, Flutter (the framework that Frosty is built upon) doesn't officially support TVs just yet. Hopefully, they'll add support for it in the future. More details in #126 if you're curious. Sorry about this.
