### ISSUE TITLE
Channel points and bonuses

### ISSUE THREAD

**Issue by juanfra684** [tommyxchow/frosty#211]
**Is your feature request related to a problem? Please describe.**
Frosty doesn't have support to see the channel points and claim the channel point bonuses.

**Describe the solution you'd like**
Add support to see and claim channel points. If possible, with bonus auto-claim support like the BTTV browser extension has. I'm not asking for an option to redeem the points (that's up to you).

**Describe alternatives you've considered**
The only alternative is the official app.

**Comment by EldritchEevee** [comment]
The ONLY App that supports Channel Points IS the Twitch App. Everything else has to use a proxy (and if you're using a proxy, surprise, you don't get channel point support.)

**Comment by tommyxchow** [comment]
As @EldritchEevee explained, unfortunately only official Twitch apps have access to channel points, bonuses, etc. Given how more and more limited Twitch's APIs have become, I don't see this being implemented for the foreseeable future. 

Sorry about this. Hopefully, this changes!

**Comment by cyriotic3** [comment]
hopefully you can at least add Auto points collecting, Xtra for Twitch has this feature

**Comment by cyriotic3** [comment]
> As @EldritchEevee explained, unfortunately only official Twitch apps have access to channel points, bonuses, etc. Given how more and more limited Twitch's APIs have become, I don't see this being implemented for the foreseeable future.
> 
> Sorry about this. Hopefully, this changes!

hopefully you can at least add Auto points collecting, Xtra for Twitch has this feature
