### ISSUE TITLE
Tapping on an Emote brings up information on it.

### ISSUE THREAD

**Issue by AustinHolderr** [tommyxchow/frosty#215]
**Is your feature request related to a problem? Please describe.**
Currently, tapping on any emote used in the Frosty app in a chat, does nothing.

**Describe the solution you'd like**
Tapping on any emote used in a stream chat brings up information on the emote (like it does in the native Twitch app and on apps like Chatterino on PC when you hover over it) such as name, channel it’s from (if & when applicable), whether it’s a global, follow, subscriber (with tier specification), or bit (with amount specification) emote, etc.…

**Describe alternatives you've considered**
Switching every time between Frosty and the native Twitch app to accomplish this, though that’s extremely counter-productive, as by the time you do that it doesn’t even matter anymore.

**Additional context**
N/A.

**Comment by AustinHolderr** [comment]
Maybe when it shows the channel name too, you can tap on that to go to the channel or something? Not too important but that would be pretty nice too.

**Comment by tommyxchow** [comment]
Hey there, apologies for the late response and thank you for bringing this up!

You can already bring up emote/badge information tooltips by long-pressing them. But as you mentioned, a tapping gesture is more standard and natural, so I've changed the gesture for badges, emotes, and usernames to tap. Will be landing in the next release!
