### ISSUE TITLE
Watch past streams on app

### ISSUE THREAD

**Issue by Zackarysabers** [tommyxchow/frosty#216]
It's been a good experience using your app, but I find it annoying when I can't watch past streams, because I'm not following lots of people so there are some times when nobody is streaming, and even if I go to search and look up a certain streamer, if they aren't streaming I can't even access past streams. If you can please add the ability to view past streams. Thanks ☺

**Comment by tommyxchow** [comment]
Unfortunately, as with many missing features, Twitch does not support VOD chats in their current API (more details in https://github.com/tommyxchow/frosty/issues/134). Sorry about this.
