### ISSUE TITLE
wish i could watch channel vods through the app

### ISSUE THREAD

**Issue by tawzeeh** [tommyxchow/frosty#225]
i don't always use twitch to watch streams, sometimes just want to watch part of the vods with chat.

Would love it if you could watch the vods through the app

Other than that, i'm satisfied with the app, thank you mister dev keep up the good work, xqcL.

**Comment by tommyxchow** [comment]
Unfortunately, as with many missing features, Twitch does not support VOD chats in their current API (more details in https://github.com/tommyxchow/frosty/issues/134). Sorry about this.

Regardless, thank you for the kind words xqcL :)!
