### ISSUE TITLE
tvOS App

### ISSUE THREAD

**Issue by slutfarm** [tommyxchow/frosty#227]
**Describe the solution you'd like**
a tvOS app for frosty would be amazing as I mostly like to watch twitch on my apple tv

**Comment by tommyxchow** [comment]
Hey there, unfortunately Flutter (the framework that Frosty is built upon) doesn't officially support TVs just yet. Hopefully they'll add support for it in the future. More details in https://github.com/tommyxchow/frosty/issues/126 if you're curious. Again, sorry about this.
