### ISSUE TITLE
Send button spamming

### ISSUE THREAD

**Issue by Bawarhama** [tommyxchow/frosty#244]
**Describe the bug**
actually there is not enough code to prevent from users who didn’t follow or have verified phone number, to don’t be able to send messages until they verify their phone numbers and follows the channels, like a original twitch app so that also mean the streamer or the mods can’t ban the account or delete the messages.

**To Reproduce**
1.  'log in'
2. 'fast tapping the send button' 
3. 'the spamming messages will be send to streamer without following or phone verification'
4. (there is no error)

**Expected behavior**
Anyone can actually send any message to a streamers without following their channel, also without phone number verification.

**Screenshots**
sorry I don’t have screenshots but devs can testing it.

**Smartphone (please complete the following information):**
 - Device: [iphone 12 pro max]
 - OS: [ios 16.3]
 - App Version: [check in Settings -> Other -> About Frosty. V3.0.1 (34)]

**Additional context**
fix this problem would help the twitch community and streamers safer and make the app better place, also prevent ur app from getting banned from twitch, and also much appreciation for this useful app.

**Comment by alienware377** [comment]
This doesn't make any sense, as this is possible in every twitch environment on both desktop and mobile. Most streamers don't turn on follower only mode, and mods can still ban them. Seems like you don't have much experience with twitch yet...
