### ISSUE TITLE
Emotes not showing up (recently)

### ISSUE THREAD

**Issue by ASSASSIN111305** [tommyxchow/frosty#260]
My emotes aren't showing up. Simple as that. I don't think I changed any settings that could have caused this. Think it's on your end.

**Comment by ASSASSIN111305** [comment]
> My emotes aren't showing up. Simple as that. I don't think I changed any settings that could have caused this. Think it's on your end.

Yo wtf. As soon as I sent this I open Frosty back up and the emotes are showing. tf going on bruh.

**Comment by tommyxchow** [comment]
Strange...maybe there was a brief downtime with one of the emote providers.

Since this seems to be fixed I'll close the issue.
