### ISSUE TITLE
Emote search not working on 3.1.2

### ISSUE THREAD

**Issue by Jnosh** [tommyxchow/frosty#266]
**Describe the bug**
Since the latest update, emote search isn't working for me anymore.

The first letter seems to be used initially but further letters are ignored so the search isn't narrowed down.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 inch, 5th gen
 - OS: 16.5
 - App Version: 3.1.2

**Comment by ParaDew** [comment]
Just wanted to add that I am also seeing this issue
Device:  Iphone XR
OS: 16.3.1
App Version: 3.1.2 (38)

**Comment by tommyxchow** [comment]
Reproducible for me as well. I think it was caused by an update/bug fix in one of the packages (MobX).

Have a fix already and will push it soon!
