### ISSUE TITLE
Other Channel’s Subscriber Emotes Not Showing

### ISSUE THREAD

**Issue by moonphased** [tommyxchow/frosty#274]
Emotes for Channels I subscribed for are not showing up in other channels. Say if I’m in Xs channel. Y and Z’s emote don’t appear even though I’m subscribed. Also animated subscriber emotes aren’t showing up in general.

Version 3.1.4 (40)

IOS 16.4 Iphone 14

**Comment by jjnapier1940** [comment]
same issue on my end all the emotes from streamers i am currently subscribed to is blacked out and can’t use them on the frosty app. went on normal twitch and all the emotes is fine. 

v 3.1.4 (40)

**Comment by Cyborgeagle** [comment]
Same issue here too. Android Version 3.1.4 (40)

**Comment by tommyxchow** [comment]
Should be fixed now in the latest version (v4.0..0+) by #281.
