### ISSUE TITLE
Video signal freezes on Android Frosty app  ver.3.1.4

### ISSUE THREAD

**Issue by Foplar** [tommyxchow/frosty#276]
After a few seconds of watching the stream, it's freezes on one frame but audio is still playin,

1. Go to any stream
2. Wait
3. See error

 - Device: Xiaomi 11t pro
 - OS: Android 13 (MIUI 14.0.3.0)
 - App Version: 3.1.4

Chat is fine, audio not interrupted when freezes, and the video stops

**Comment by chanawitonchoo** [comment]
Happen to me too.
Device: Samsung S23 Ultra
OS: Android 13 (OneUI 5.1)
App Version: 3.1.4

**Comment by Arc-Jung** [comment]
@Foplar @conchoo2 
You should upload screen shot.
I do not view error.

**Comment by conchoo2** [comment]
> @Foplar @conchoo2 You should upload screenshot. I do not view error.
> 
> Device: Samsung Galaxy Fold 4 OS: Android 13 (OneUI 5.1.1) App Version: 3.1.4
> 
> Device: Apple iPhone 14 Pro Max OS: iOS 16.5 App Version: 3.1.4

Hi, I'm not sure how but the issue is not happened anymore. On my Samsung s23 ultra.

**Comment by Foplar** [comment]
I just checked, and it seems it had been fixed somehow, maybe it was some android problem or Android System WebView

**Comment by Foplar** [comment]
I just checked, and it seems it had been fixed somehow, maybe it was some android problem or Android System WebView

**Comment by Arc-Jung** [comment]
@Foplar Ok. I checked this case. See you again.
