### ISSUE TITLE
Some of my followed streamers are covered in closed captioning

### ISSUE THREAD

**Issue by bruhcomeatme12** [tommyxchow/frosty#279]
Certain twitch streamers I watch will have closed captioning blocking the stream on Frosty as if I have it turned on even though I never turned it on and can't turn it off.(it is always on the same streamers no matter if I close and restart the app or if I turn off and back on my iphone)

1. Go to Frodan(https://www.twitch.tv/frodan) or Robinsongz (https://www.twitch.tv/robinsong)
2. Wait couple of seconds 
3. Screen gets filled with CC

Screenshots: https://www.dropbox.com/scl/fo/zrltj8gwtadhytcexalk7/h?rlkey=m9zl9k577fdt7cjywduurxkwt&dl=0
This problem is on my iphone 12

**Comment by tommyxchow** [comment]
Hi, thank you so much for the detailed report! I was able to repro it - turns out iOS turns on subtitles/cc on by default on videos and I never caught it (perhaps a side effect from the recent iOS versions). Landed a fix that'll arrive in the next update.
