### ISSUE TITLE
7tv fixed

### ISSUE THREAD

**Issue by Zwyroleeex** [tommyxchow/frosty#286]
hello, my problem is that the 7tv emotes do not land and I do not want to use them in the chat whenever I want to enter the 7tv emotes, I don't see them at all, I don't know what causes this error when the day before I had normal emotes,
application version 4.0.0
phone: samsung A34 android 13
thank you in advance for your help

**Comment by jedi-scholar** [comment]
7tv emotes are not loading at all for me.  The emote section is completely blank for any channel i go to.  Was working fine a few days ago.
Version 4.0.0
iOS 16.6.1

**Comment by tommyxchow** [comment]
Hey all, did some investigating and discovered that 7TV changed their API today (v2 API shutdown in favor of v3). Unfortunately I totally missed the announcement, will land a fix by today. Sorry!
