### ISSUE TITLE
7tv emotes

### ISSUE THREAD

**Issue by CAalllDay** [tommyxchow/frosty#288]
**Describe the bug**
7tv global and channel emotes are not loading in the app. I can’t use nor see them in chat

**Comment by tommyxchow** [comment]
Hello! I've landed a fix for this in #287 and submitted to the app stores, should be released today if approval goes quickly.

If you're on Android, you can install the APK for the release over [here](https://github.com/tommyxchow/frosty/releases/tag/v4.0.1) for now.

Duplicate of #286. Will leave this open until the update is out for visibility.

**Comment by CAalllDay** [comment]
Awesome thank you! I'm an Apple user.
