### ISSUE TITLE
Frosty does not recognize when a channel has a custom name for a 7tv emote

### ISSUE THREAD

**Issue by kenbeck13** [tommyxchow/frosty#289]
**Describe the bug**
Frosty only recognizes the default name for 7tv emotes. If the channel changed the name for an emote, the new name will not autofill, and the new name will not show as the emote in the chat.

**To Reproduce**
1. Join a stream chat who has a 7tv emote with a different name than its default name.
2. Start entering the new name into the chat bar. It will not autofill.
3. Finish typing the emote and click send. It will not show as the emote in your chat.
4. The emote will appear to be correct in other viewers/the streamer's chat.

**Expected behavior**
The emote should only appear as the new name.

**Smartphone (please complete the following information):**
 - Device: Galaxy S22
 - OS: Android v13
 - App Version: 4.0.1

**Additional context**
This worked correctly prior to 4.0.0

**Comment by tommyxchow** [comment]
Thank you so much for reporting this! I wrongly assumed that the 7TV API handled the naming automatically and did not realize it.
