### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by Schlafanzug** [tommyxchow/frosty#293]
Could you please port this app to Windows?
The Twitch clients I have seen so far either don't have chat or are just VLC streams.
But your app has the stream(no ads), chat, categories and 3rd party emotes.
So your app as a windows program would be perfect.

**Comment by Arc-Jung** [comment]
Unfortunately Windows app is not supported. But you should use Twitch third party chrome browser extension(Microsoft Edge extension).

> https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf
