### ISSUE TITLE
Multiple text lines clip chat box edges

### ISSUE THREAD

**Issue by dezponia** [tommyxchow/frosty#296]
**Description of bug**
Write multiple lines of text in the chat box and the message text will start to overlap/clip the rounded edges of the chat box.

**To Reproduce**
1. Open a stream
2. Type a message that hits 3+~ lines of text
3. Observe how the written text starts to overlap/clip the rounded outline "corners" of the chat box.

**Expected behavior**
Entered text should stay within the chat box outline. Perhaps the outline corners/edges should be less aggressively rounded?

**Screenshot**
![Frosty 4 0 2 chat box text overflow](https://github.com/tommyxchow/frosty/assets/150628177/71fcf625-e21b-41d4-b950-cf7d59ce4fab)

**Smartphone:**
 - Device: Fairphone 5
 - OS: Android 13
 - App Version: Frosty 4.0.2 (43)

**Comment by tommyxchow** [comment]
Thank you for catching this! I've gone ahead and tweaked the paddings. Also reduced the max lines from 5 to 3 since the former seemed excessive for a mobile interface.

![image](https://github.com/tommyxchow/frosty/assets/54859075/30984bb5-94ba-4a33-a15e-7bf8c78394e1)
