### ISSUE TITLE
App crashes on iOS 12

### ISSUE THREAD

**Issue by Jo7717** [tommyxchow/frosty#303]
Whenever I open the app it closes immediately, I've uninstalled and reinstalled it and even formatted the phone and it still doesn't open 

-IPhone 6

-IOS 12.5.7

-Frosty App version 4.1.0

**Comment by tommyxchow** [comment]
Hello, so far this is very likely related to Flutter 3.16 which was shipped with Frosty v4.1.0.

As reported by other users, only iOS 12 seems to be crashing (more details [here](https://github.com/flutter/flutter/issues/135317)). We'll have to wait until a hotfix releases from the Flutter/Google team for that. Unfortunately, I don't know exactly how long that will take.

If you need an alternative app and don't have it already, I recommend using [Chatsen](https://chatsen.app/) for the time being.

**Comment by SputNikPlop** [comment]
@tommyxchow as of 3.16.5 this has been fixed works against my one iOS 12 device

**Comment by tommyxchow** [comment]
> @tommyxchow as of 3.16.5 this has been fixed works against my one iOS 12 device

Awesome - going to submit an update soon to the app stores as well with Flutter 3.16.5.
