### ISSUE TITLE
Missing username in chat app v4.2.0

### ISSUE THREAD

**Issue by sun-wise-man** [tommyxchow/frosty#308]
**Describe the bug**
My username is missing in chat. Only badge and the message

**To Reproduce**
1. Send a message in app v4.2.0

**Expected behavior**
Username is showing up

**Screenshots**
Here's in desktop browser
![Screenshot 2023-11-30 at 20-49-17 CDawgVA - Twitch](https://github.com/tommyxchow/frosty/assets/67572372/433eaf0c-398d-4163-a0c9-c6f66c48471b)

Here's in app
![image0](https://github.com/tommyxchow/frosty/assets/67572372/48f64e16-9061-470e-b75f-f29788aa073b)

**Smartphone (please complete the following information):**
 - Device: Samsung M23
 - OS: Android 13
 - App Version: v4.2.0
 
 **Additional context**
I think it only happens in v4.2.0, because when I downgraded username is showing up.

**Comment by tommyxchow** [comment]
Thanks for reporting this - can reproduce it on my end as well. Will get a fix out by tonight.
