### ISSUE TITLE
I am subbed to a channel but I still get ads. I am not sure why

### ISSUE THREAD

**Issue by tamusandesh99** [tommyxchow/frosty#311]

**Comment by richchestmat** [comment]
I have the same issue and had to stop using Frosty and go back to the official Twitch client as ads were interrupting too much.

**Comment by tommyxchow** [comment]
If you haven't already, could you try logging out and in again? This will re-trigger Frosty to log in to Twitch correctly in case it failed the first time.

**Comment by richchestmat** [comment]
Thanks. Logging out and back in fixed this.
