### ISSUE TITLE
Stream never starts 

### ISSUE THREAD

**Issue by Enkirex** [tommyxchow/frosty#326]
**Describe the bug**
After selecting a stream the video never starts but the chat is scrolling without problems

**To Reproduce**
1. Open the app
2. Select a stream
4. Wait

**Expected behavior**
The video stream should start playing 

**Screenshots**
![IMG_0005 1](https://github.com/tommyxchow/frosty/assets/73191398/7ec3558c-3228-460c-8760-893adb4bdd33)
![IMG_0006 1](https://github.com/tommyxchow/frosty/assets/73191398/dd3837c5-8586-4ec9-8449-1e9e94d82c41)
![IMG_0007 1](https://github.com/tommyxchow/frosty/assets/73191398/7d2569f7-7275-471b-a227-715cbce65f70)

**Smartphone (please complete the following information):**
 - Device: iPhone 5c,
 - OS: iOS 10.3.3
 - App Version: 2.2.0 (30)

**Additional context**
I know that the OS and the device are really old but I used to watch Twitch without problems on its oficial app, unafortunaly I uninstalled it an the last working version (8.0) has since been purged from the App Store, so I'm willing to do anything; my device is Jailbroken and I can Sideload apps.

**Comment by tommyxchow** [comment]
Hi, unfortunately Flutter only officially support iOS 12 and later, so features aren't guaranteed to work for versions below that. Sorry about this.
