### ISSUE TITLE
Animated FFZ emotes stuck on 1st frame

### ISSUE THREAD

**Issue by huggernautxl** [tommyxchow/frosty#327]
**Describe the bug**
See title. The animated FFZ emotes don’t animate correctly, they all seem to be stuck on the first frame. All other animated emotes (Twitch, 7TV, and BTTV) function normally, it’s just the animated FFZ emotes that don’t work. No other issues with the regular FFZ emotes.

**Screenshots**
![IMG_1604](https://github.com/tommyxchow/frosty/assets/157125298/6c46a987-ac90-4e0d-a683-140e39244b7e)
![IMG_1605](https://github.com/tommyxchow/frosty/assets/157125298/bc41e721-ced4-4b8b-9fb0-a7ea1931255f)
![IMG_1606](https://github.com/tommyxchow/frosty/assets/157125298/0882755e-a314-4645-8064-ff85eb19c24f)

**Smartphone:**
 - Device: iPhone 8 Plus
 - OS: iOS 16.7.4
 - App Version: 4.3.0

**Comment by Lordmau5** [comment]
From a look at the code it looks like animated emotes aren't properly destructured / handled from the FFZ API response.

Someone on the FFZ discord reported it a bit ago as well and I thought I had a look
https://github.com/tommyxchow/frosty/blob/main/lib/models/emotes.dart#L249

It seems it's only using the static URLs and not the animated URLs in this factory method
