### ISSUE TITLE
None of the add on emotes showing(7tv bttv ffz)

### ISSUE THREAD

**Issue by clcl2024** [tommyxchow/frosty#328]
None of the emotes besides the base twitch emotes are showing.

Ive tried reinstalling the app.
![1BF1DA97-9DFA-4AE7-942D-83C436A10A4E](https://github.com/tommyxchow/frosty/assets/160980717/2eaf5388-19de-4b31-8153-8e969fac9b44)
![DBEB4946-5385-41A9-8C65-71FF2BD4710F](https://github.com/tommyxchow/frosty/assets/160980717/696bd08e-fcc1-49b8-8ccf-4b355df9a632)
![5FC39806-19C1-4593-A6EF-88C2394A14EC](https://github.com/tommyxchow/frosty/assets/160980717/a69cd7a0-3685-435b-b00e-c0b9e89b08fe)
![3D4FA167-DBB7-4A97-999D-F592A1A246FD](https://github.com/tommyxchow/frosty/assets/160980717/437fe397-1590-48d8-b80f-dcef07a4d649)

**Smartphone (please complete the following information):**
 - Device: iphone 13 mini
 - OS: ios 16.3.1
 - App Version: 4.3.0

**Comment by Habaski** [comment]
how did you solve this problem?

**Comment by clcl2024** [comment]
> how did you solve this problem?

It just fixed itself, I thought the author saw this and did something
