### ISSUE TITLE
Chat only mode

### ISSUE THREAD

**Issue by MrKnitler** [tommyxchow/frosty#343]
Hey, it would be great if you could add a **Chat only mode** in the near future.

Because I am always watching on my TV this would be a great addition.

**Comment by tommyxchow** [comment]
Hello, a chat-only mode already exists but it's not as distinct as I had thought. Currently, you can go into chat-only mode by going to settings -> video and toggling "Enable video" to off.

The next update will feature a dedicated button in the chat menu (three dots button) to toggle chat-only mode (#350).
