### ISSUE TITLE
Chat without video

### ISSUE THREAD

**Issue by jimmycuadra** [tommyxchow/frosty#354]
Hi there! Thanks very much for Frosty! I'm happy to have a good alternative to the official Twitch app.

I watch Twitch primarily on Apple TV and use my phone just for chatting. For that reason, when using the official Twtich app, I go directly to the profile of the streamer I'm watching and switch to the "chat" tab so that I get a full-screen chat without the actual stream.

Currently in Frosty, I just pause the stream video in the app, since there isn't a way to hide it completely. This works okay, but takes up a pretty significant amount of screen real estate on a mobile phone. It would be fantastic to have a way to hide the video completely, or better yet, a separate page for just chatting so Frosty doesn't have to load the stream video in the first place.

Thanks for considering!

**Comment by dmizelle** [comment]
I use the functionality provided by the toggle in the attached screenshot. Have you tried that and seen if that works for you? It's app-wide and requires you to close the stream and toggle it on/off so it's not 100% equivalent but I find it to be close enough.

![Screenshot_20240627-210919.png](https://github.com/tommyxchow/frosty/assets/296298/9a1697f8-9e7c-4e4e-a8c8-6f6799c3e874)
