### ISSUE TITLE
App force closes itself

### ISSUE THREAD

**Issue by JBrown-3** [tommyxchow/frosty#367]
The app force closes itself while watching a stream every 30 minutes. I do not have the sleep timer on. This has been happening for the current update and the update before I believe.

**Smartphone **
 - Device: Pixel 7
 - OS: Android 14
 - App Version: 4.3.1

**Comment by akuntsch** [comment]
Also experiencing frequent crashes/force closes here.
I can provide a logcat.

Device: Google Pixel 8 Pro
OS: Stock Android 14
App Version: 4.6.0

**Comment by FreddyOriginal** [comment]
Have been experiencing the same for the past ~2 months.
I've started using this app shorty after verion 4.4.0 was released. Back then, the crashes only happened occasionally or maybe I just wasn't using the app long enough at a time.
With every update, it seems to happen earlier. Additionally, short ~2 second freezes are now happening in random intervals, usually every 5-10 minutes if I had to guess, until the app finally either crashes/freezes entirely or only the UI locks up but the audio still continues.

Device: Google Pixel 6a
OS: Android 14
App version: 4.6.0

**Comment by tommyxchow** [comment]
Hey all, this should be fixed with >v4.8.0 (commit at https://github.com/tommyxchow/frosty/commit/362977c36025006b93997cfde0529db04c664ec9). Please re-open if not.

v4.9.0 also has an option to toggle this for those not facing the crashes.
