### ISSUE TITLE
Issue with the twitch cookie overlay when logging in.

### ISSUE THREAD

**Issue by UmmonTeal** [tommyxchow/frosty#380]
**Describe the bug**
I was unable to log into my twitch account. When trying I after seeing the login screen for half a second, the twitch cookie notification overlay blocks it. But while I could zoom and scroll around on it, the buttons to accept the cookies were missing. I managed to solve this by clicking on the links for the cookie policy and clicking around until I found a link back to the twitch website. There I was able to accept the cookies which then allowed me to login on Frosty without the overlay.

**To Reproduce**
1. Start the App after a fresh install/with cleared cache
2. Open the Settings
3. Click on Anonymous to log in
4. cookie overlay pops up

**Expected behavior**
I would expect the buttons to accept/reject/customize the cookie settings.

**Screenshots**
---

**Smartphone (please complete the following information):**
 - Device: Samsung Ultra S21
 - OS: Android 14
 - App Version: 4.4.0 (50)

**Comment by UmmonTeal** [comment]
Since I managed to solve the issue I'll close it immediately. Hopefully it helps if others have the same problem.

**Comment by tommyxchow** [comment]
Hey there, thanks for providing a solution. I'm going to re-open this issue just so I can reference it in a potential fix/workaround I'm working on.
