### ISSUE TITLE
Chat history encoding issue

### ISSUE THREAD

**Issue by dayyakav** [tommyxchow/frosty#396]
**Describe the bug**
Frosty does not display Russian letters in historical messages correctly.

**To Reproduce**
1. Turn on «Show historical recent messages»
2. Go to any Russian channel chat (e.g. T2x2)
3. See character encoding issue

**Expected behavior**
Correct encoding of Russian letters

**Screenshots**
![image](https://github.com/user-attachments/assets/4e672d5b-8e5c-4f27-abed-911c48adb2f4)

**Smartphone:**
 - Device: iPhone 12
 - OS: iOS 17.4.1
 - App Version: v4.5.0 (51)

**Additional context**
Frosty perfectly works on streams and new messages in chat. This issue happens only with historical messages and only with Russian letters (as i see)

Also this function works correctly in Chatsen. So I hope it can be easily fixed

(Sorry for english, used translator)

**Comment by tommyxchow** [comment]
Thank you for reporting this! The details were very helpful. Fixed in 1938fb910de52582929cb331e56eff9bc4c8e908
