### ISSUE TITLE
Can we get the ability to filter chat messages, please?

### ISSUE THREAD

**Issue by valfaun** [tommyxchow/frosty#400]
Hi. Would it be feasible to implement a message filter functionality? Something like what FFZ or Chatterino offer, maybe. 
I realize that it's a personal issue, but there are certain words and 7TV emotes that I'd really rather not see in the interest of my emotional health... And maybe others could also benefit from hiding undesirable or annoying terms

**Comment by zeykafx** [comment]
That's a great idea. I will try to implement it and make a pull request.
