### ISSUE TITLE
v4.8.0 7TV / BTTV / FFZ Emoji not loading on iOS and Android

### ISSUE THREAD

**Issue by timconner** [tommyxchow/frosty#425]
**Describe the bug**
On version 4.8.0, the 7TV, BTTV, and FFZ emojis are not loading. The emoji cards contain only the "Global" tab which is empty and no "Channel" tab. 

**NOTE:** It does not appear to affect every channel, but it does affect most.

Additionally, emojis from respective providers do not resolve/render (e.g. KEKW just shows as text).

**To Reproduce**
1. Install version 4.8.0.
2. Open any stream.
3. Inspect available emojis.

**Expected behavior**
All channel and global 7TV, BTTV, and FFZ emotes should be available.

**Screenshots**
4.7.1
![4 7 1](https://github.com/user-attachments/assets/2e64e8f4-85af-4d14-a7f0-085389464155)

4.8.0
![4 8 0](https://github.com/user-attachments/assets/ec638bc5-b771-4e7c-b6b5-7587ff03ca1c)

**Smartphone (please complete the following information):**
 - Device: Pixel 8 & iPhone
 - OS: Android 15 (also confirmed on iOS via friend).
 - App Version: 4.8.0 (55)

**Additional context**
The issue does not appear after reinstalling version 4.7.1 on Android.

**Comment by tommyxchow** [comment]
Thanks for the bug report - can you give me some of the channels you've observed this happening on?

**Comment by timconner** [comment]
The one I've confirmed happens on both Android and iOS is BarbarousKing.

A couple others I've observed: Chatterbox, DashDucks

**Comment by tommyxchow** [comment]
> The one I've confirmed happens on both Android and iOS is BarbarousKing.
> 
> A couple others I've observed: Chatterbox, DashDucks

Thank you so much for the details - landed a fix and will push a release soon!
