### ISSUE TITLE
Custom player with support for nodelay and PiP?

### ISSUE THREAD

**Issue by mutahert** [tommyxchow/frosty#76]
I think this would finally solve the issue of watching Twitch on iOS without delay and being able to see third party emotes. Maybe having experiments menu in settings for this? Not having Picture-in-Picture wouldn't be such a big deal but would be cool to see it in the app

**Comment by tommyxchow** [comment]
> I think this would finally solve the issue of watching Twitch on iOS without delay and being able to see third party emotes. Maybe having experiments menu in settings for this? Not having Picture-in-Picture wouldn't be such a big deal but would be cool to see it in the app

I wish I could have this implemented, but the low latency feature that the official Twitch app has appears to be a private/proprietary feature without any sort of documentation. Perhaps there will be more information about it in the future (hopefully).

Here's some extra explanation from another post if you're interested:


I previously looked into implementing the low latency mode on Twitch, but unfortunately there wasn’t any documentation relating to it. Furthermore, Twitch doesn’t have an official public API for getting HLS stream links (there is a private API codenamed “usher”, but it has been mentioned that it violates their TOS if used).

The video right now is essentially a browser that links to the embed URL in full screen, hence why you can’t really do things like change the quality on iOS for example. I wish I could do better here, but sadly I’m mostly limited by what’s allowed in the API.

**Comment by mutahert** [comment]
> > I think this would finally solve the issue of watching Twitch on iOS without delay and being able to see third party emotes. Maybe having experiments menu in settings for this? Not having Picture-in-Picture wouldn't be such a big deal but would be cool to see it in the app
> 
> I wish I could have this implemented, but the low latency feature that the official Twitch app has appears to be a private/proprietary feature without any sort of documentation. Perhaps there will be more information about it in the future (hopefully).
> 
> Here's some extra explanation from another post if you're interested:
> 
> I previously looked into implementing the low latency mode on Twitch, but unfortunately there wasn’t any documentation relating to it. Furthermore, Twitch doesn’t have an official public API for getting HLS stream links (there is a private API codenamed “usher”, but it has been mentioned that it violates their TOS if used).
> 
> The video right now is essentially a browser that links to the embed URL in full screen, hence why you can’t really do things like change the quality on iOS for example. I wish I could do better here, but sadly I’m mostly limited by what’s allowed in the API.

Hmm the Xtra app has a custom player and its open-source: https://github.com/crackededed/Xtra
Would this be useful in any way? Also I'm jailbroken so I can try to help with finding something that could be useful in the files of the Twitch app

**Comment by tommyxchow** [comment]
> Hmm the Xtra app has a custom player and its open-source: https://github.com/crackededed/Xtra Would this be useful in any way? Also I'm jailbroken so I can try to help with finding something that could be useful in the files of the Twitch app

Xtra is Android-only so the behavior is quite different than iOS (e.g., the video player for Frosty on Android actually has no delay).

I'm pretty sure Xtra also uses the "usher" API I mentioned before with some ad-blocking, but iirc the app was taken down by Twitch from the Play Store. For Frosty, I don't want to tread too much on private APIs or reverse-engineering methods because staying on the app stores is one of my highest priorities.

I hope you understand, and thank you regardless.

**Comment by mutahert** [comment]
> > Hmm the Xtra app has a custom player and its open-source: https://github.com/crackededed/Xtra Would this be useful in any way? Also I'm jailbroken so I can try to help with finding something that could be useful in the files of the Twitch app
> 
> Xtra is Android-only so the behavior is quite different than iOS (e.g., the video player for Frosty on Android actually has no delay).
> 
> I'm pretty sure Xtra also uses the "usher" API I mentioned before with some ad-blocking, but iirc the app was taken down by Twitch from the Play Store. For Frosty, I don't want to tread too much on private APIs or reverse-engineering methods because staying on the app stores is one of my highest priorities.
> 
> I hope you understand, and thank you regardless.

Well that really sucks. It seems like only jailbroken users will get to experience no delay Twitch with emotes before Twitch implements BTTV in their own app :/
Have you thought about getting into the jailbreaking scene and maybe making a paid a tweak that would work with your app? Could be an option without worrying about getting kicked from the stores. Thanks for all the quick replies so far!

**Comment by tommyxchow** [comment]
> Well that really sucks. It seems like only jailbroken users will get to experience no delay Twitch with emotes before Twitch implements BTTV in their own app :/ Have you thought about getting into the jailbreaking scene and maybe making a paid a tweak that would work with your app? Could be an option without worrying about getting kicked from the stores. Thanks for all the quick replies so far!

Definitely a good idea/workaround. I'm not the biggest fan of UIKit/Objective-C, but if I manage some extra time in the future for another side-project I may look into it (don't want to make any promises!).

**Comment by mutahert** [comment]
> > Well that really sucks. It seems like only jailbroken users will get to experience no delay Twitch with emotes before Twitch implements BTTV in their own app :/ Have you thought about getting into the jailbreaking scene and maybe making a paid a tweak that would work with your app? Could be an option without worrying about getting kicked from the stores. Thanks for all the quick replies so far!
> 
> Definitely a good idea/workaround. I'm not the biggest fan of UIKit/Objective-C, but if I manage some extra time in the future for another side-project I may look into it (don't want to make any promises!).

Nice :) Make sure to not update your iOS so you can jailbreak in the future 👍 :D
